import { Constraints, TeamSize, Budget, Scale, Project } from "../types";
import poassReadme from "../content/poasstereo.md?raw";
import acnrReadme from "../content/acnr.md?raw";
import sendaReadme from "../content/senda.md?raw";
import portfolioReadme from "../content/portfolio.md?raw";

export const INITIAL_CONSTRAINTS: Constraints = {
  teamSize: TeamSize.SMALL,
  budget: Budget.VENTURE,
  scale: Scale.REGIONAL,
  realtime: false,
  deadline: 6,
};

export const PROJECTS: Project[] = [
  {
    id: "senda",
    title: "SENDA",
    description: "5-role work-scholarship portal for UNADECA's Horas Beca program. Replaces spreadsheets with a structured digital workflow: students log hours → department heads approve → accounting consolidates payroll → branded PDF/CSV export. Features per-role code splitting (React.lazy), 32 Vitest unit tests for all billing logic, ESLint 0-warning policy enforced via Husky pre-commit hooks, and GitHub Actions CI on every push.",
    description_es: "Portal de becas laborales con 5 roles para el programa Horas Beca de UNADECA. Reemplaza hojas de cálculo con un flujo digital: estudiantes registran horas → jefes de departamento aprueban → contabilidad consolida planilla → exportación PDF/CSV institucional. Incluye code splitting por rol (React.lazy), 32 pruebas unitarias en Vitest, política 0 warnings con ESLint + Husky pre-commit y CI en GitHub Actions.",
    techStack: ["React 19", "TypeScript", "Vite", "Tailwind 4", "Vitest", "jsPDF", "Recharts", "Motion 12", "GitHub Actions"],
    relevanceScore: 0,
    status: "WIP",
    teamRole: "solo",
    year: "2026",
    githubUrl: "https://github.com/Marvs04/senda_unadeca",
    readme: sendaReadme,
    problem: "UNADECA managed scholarship hours with spreadsheets: no audit trail, no visibility for students, no automated payroll — department heads hunted down correct hour counts manually every billing cycle.",
    problem_es: "UNADECA gestionaba las horas beca con hojas de cálculo: sin trazabilidad, sin visibilidad para estudiantes, sin planilla automatizada — los jefes de departamento calculaban horas manualmente cada ciclo.",
    currentChallenge: "All billing-cycle calculation, trimester detection and payroll math live in a pure business.ts — no React, no DOM — which is what makes 32 deterministic unit tests possible. The mock→real Supabase swap is one environment variable; no component changes needed.",
    currentChallenge_es: "Toda la lógica de ciclos de facturación, detección de trimestres y cálculo de planilla vive en un business.ts puro — sin React, sin DOM — lo que permite 32 pruebas unitarias deterministas. El cambio de mock a Supabase real es una sola variable de entorno, sin tocar componentes.",
    lessonLearned: "Business logic is only testable if it has no framework dependencies. Separating it from React from day one made 32 unit tests trivial — and made the Supabase migration a config change, not a rewrite.",
    lessonLearned_es: "La lógica de negocio solo es testeable si no tiene dependencias del framework. Separarla de React desde el inicio hizo que 32 pruebas fueran triviales y que la migración a Supabase fuera un cambio de configuración, no una reescritura.",
  },
  {
    id: "acnr",
    title: "ACNR Website",
    description: "Public site for the Asociación Norte de Costa Rica: church locator with coordinate parsing from Maps URLs, Strapi 5 as headless CMS (correctly handles the v5 flat response schema), and hybrid SSR/static routing — church filter runs server-side, everything else is prerendered. Graceful fallback to mock data when CMS is down means the app always renders in CI, local dev, and demos.",
    description_es: "Sitio público de la Asociación Norte de Costa Rica: localizador de iglesias con parsing de coordenadas desde URLs de Maps, Strapi 5 como CMS headless (maneja correctamente el schema plano de v5), y enrutamiento híbrido SSR/estático — el filtro de iglesias corre en servidor, el resto es pregenerado. Fallback a datos mock cuando el CMS no está disponible.",
    techStack: ["Astro 5", "Tailwind 4", "TypeScript", "Strapi 5", "Google Maps"],
    relevanceScore: 0,
    status: "WIP",
    teamRole: "solo",
    year: "2026",
    readme: acnrReadme,
    problem: "The association had no centralized platform for news, shared files (PDFs, Excel, presentations), or a church directory. Content had to be edited by a developer — no editorial autonomy.",
    problem_es: "La asociación no tenía plataforma para publicar noticias, compartir archivos ni mostrar un directorio de iglesias. El contenido solo lo podía editar un desarrollador — cero autonomía editorial.",
    currentChallenge: "Strapi v5 changed its response shape (dropped the nested attributes wrapper). Typed generics (StrapiListResponse<T>) absorb that at the data layer so page components never see raw CMS shapes — the CMS schema can change without touching a single component.",
    currentChallenge_es: "Strapi v5 cambió su estructura de respuesta (eliminó el wrapper de atributos anidados). Los genéricos tipados (StrapiListResponse<T>) absorben eso en la capa de datos para que los componentes de página nunca vean formas raw del CMS — el schema puede cambiar sin tocar un solo componente.",
    lessonLearned: "Hybrid SSR/static in Astro is the right call when 90% of the site is prerenderable but one route needs query params. Doing it correctly means you get static performance everywhere except where you actually need the server.",
    lessonLearned_es: "El enrutamiento híbrido SSR/estático de Astro es la elección correcta cuando el 90% del sitio es pregenerado pero una ruta necesita parámetros de consulta. Hacerlo bien significa rendimiento estático en todo el sitio excepto donde realmente se necesita el servidor.",
  },
  {
    id: "student-path",
    title: "Student Path",
    description: "An academic management system for the Registro department at UNADECA: student grades, graduation eligibility checks, and normalization of over a decade of inconsistent CSV records.",
    description_es: "Sistema de gestión académica para el Registro de UNADECA: calificaciones, verificación de elegibilidad para graduación y normalización de más de una década de registros CSV inconsistentes.",
    techStack: ["Python", "Pandas", "PostgreSQL", "Streamlit", "Azure", "Docker"],
    relevanceScore: 0,
    status: "SHIPPED",
    teamRole: "team",
    year: "2024",
    problem: "The Registro department had CSV files dating back to 2016 with inconsistent formats, missing fields, and bad data — making automated graduation eligibility checks impossible.",
    problem_es: "El Registro tenía archivos CSV desde 2016 con formatos inconsistentes, campos faltantes y datos incorrectos — lo que imposibilitaba automatizar la verificación de elegibilidad para graduación.",
    currentChallenge: "Applying RegEx and Pandas normalization pipelines across inconsistent multi-year CSVs without data loss or incorrect student records.",
    currentChallenge_es: "Aplicar pipelines de normalización con RegEx y Pandas sobre CSVs heterogéneos de múltiples años sin pérdida de datos ni registros incorrectos.",
    lessonLearned: "Raw institutional data is always messier than expected. Build validation and audit trails into the pipeline from the start — not as an afterthought.",
    lessonLearned_es: "Los datos institucionales en crudo siempre son más caóticos de lo esperado. Las validaciones y los registros de auditoría deben integrarse al pipeline desde el inicio, no como una ocurrencia tardía.",
  },
  {
    id: "stamp",
    title: "STAMP",
    description: "A multi-user boarding-school platform for a college internado: QR-based church attendance, exit permit management, and a kiosk mode — serving students, monitors, preceptors, and guards.",
    description_es: "Plataforma multi-usuario para el internado de un colegio: asistencia a culto por QR, gestión de permisos de salida y modo quiosco — para estudiantes, monitores, preceptores y guardias.",
    techStack: ["React", "TypeScript", "JavaScript", "MUI", "Tailwind", "Express", "Supabase", "Docker"],
    relevanceScore: 0,
    status: "SHIPPED",
    teamRole: "team",
    year: "2024",
    problem: "Church attendance and student exit permits were tracked manually by staff, making enforcement slow, inconsistent, and impossible to audit.",
    problem_es: "La asistencia a culto y los permisos de salida se registraban manualmente, haciendo el control lento, inconsistente e imposible de auditar.",
    currentChallenge: "Building two distinct frontends — one for staff (MUI-based) and one for students (Neobrutalism.dev) — sharing the same Express API and Supabase backend without leaking role concerns.",
    currentChallenge_es: "Desarrollar dos frontends distintos — uno para personal (MUI) y uno para estudiantes (Neobrutalism.dev) — compartiendo el mismo backend Express + Supabase sin mezclar responsabilidades de roles.",
    lessonLearned: "QR-based flows are convenient until a device camera fails mid-session. Offline fallback paths aren't optional — they're part of the spec.",
    lessonLearned_es: "Los flujos por QR son prácticos hasta que la cámara falla en medio de una sesión. Los caminos alternativos sin conexión no son opcionales — son parte del spec.",
  },
  {
    id: "poasstereo",
    title: "POASSTEREO",
    description: "Website for a Costa Rican online radio station. Parallax hero, live radio player, real-time weather widget (Open-Meteo, no API key), live clock (CR timezone), and animated collage hero — all built with Astro's island architecture: zero JS by default.",
    description_es: "Sitio web de una emisora de radio costarricense. Hero con parallax, reproductor en vivo, widget del clima en tiempo real (Open-Meteo, sin API key), reloj en vivo (zona horaria CR) y collage animado — construido con la arquitectura de islas de Astro: cero JS por defecto.",
    techStack: ["Astro 5", "Tailwind 3", "TypeScript"],
    link: "https://poasstereo.net/",
    readme: poassReadme,
    relevanceScore: 0,
    status: "SHIPPED",
    teamRole: "solo",
    year: "2025",
    problem: "The station needed a modern web presence that loaded fast and was easy to maintain without a backend team.",
    problem_es: "La emisora necesitaba una presencia web moderna, de carga rápida y fácil de mantener sin un equipo de backend.",
    currentChallenge: "Structuring a content-first site in Astro that could be updated quickly without redeployment friction.",
    currentChallenge_es: "Estructurar un sitio orientado al contenido en Astro que pudiera actualizarse rápidamente sin fricción en el redespliegue.",
    lessonLearned: "Astro's island architecture is the right tool for content sites — ship zero JS by default and hydrate only what actually needs interactivity.",
    lessonLearned_es: "La arquitectura de islas de Astro es la herramienta correcta para sitios de contenido — envía cero JS por defecto e hidrata solo lo que realmente necesita interactividad.",
  },
  {
    id: "portfolio-v1",
    title: "This Portfolio",
    description: "A constraint-driven engineering portfolio that adapts architecture recommendations in real-time based on visitor-defined system parameters.",
    description_es: "Un portafolio de ingeniería orientado a restricciones que adapta las recomendaciones de arquitectura en tiempo real según los parámetros definidos por el visitante.",
    techStack: ["React", "TypeScript", "Motion", "Tailwind"],
    relevanceScore: 0,
    status: "SHIPPED",
    teamRole: "solo",
    year: "2026",
    readme: portfolioReadme,
    githubUrl: "https://github.com/Marvs04/brutafolio",
    problem: "Portfolios are typically static and fail to communicate how a developer reasons through trade-offs and system design.",
    problem_es: "Los portafolios suelen ser estáticos y no logran comunicar cómo un desarrollador razona ante compromisos y decisiones de diseño de sistemas.",
    currentChallenge: "Keeping the constraint engine honest and the content accurate — a portfolio that misrepresents you is worse than none.",
    currentChallenge_es: "Mantener el motor de restricciones honesto y el contenido preciso — un portafolio que te representa mal es peor que ninguno.",
    lessonLearned: "Building a tool that walks visitors through your decision-making process is more revealing than listing tech credits.",
    lessonLearned_es: "Construir una herramienta que guíe a los visitantes por tu proceso de toma de decisiones es más revelador que listar tecnologías.",
  }
];
